### ISSUE TITLE
Use Kotlin parcelize instead android-extensions

### ISSUE THREAD

**Issue by pdas9647** [sawankumarbundelkhandi/edge_detection#121]
The Android extensions ('kotlin-android-extensions') compiler plugin is no longer supported. Please use kotlin parcelize and view binding.

**Comment by maltemedocs** [comment]
Some context and workaround:

When compiling my flutter app in flutter 3.7.3, I got this warning:

```
─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /home/USER/PROJECT/android/build.gradle:                                           │
│ ext.kotlin_version = '<latest-version>'          
```
`ext.kotlin_version` was set to 1.5.31, like in this plugin (and I think because of this plugin).

According to https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html, the plugin was removed in kotlin 1.8. This would make the newest compatible version 1.7.21. So affected users can set `ext.kotlin_version = '1.7.21'` and still use edge_detection for the time being.
